### ISSUE TITLE
redundant tags after load the dataset

### ISSUE THREAD

**Issue by coffezhou** [OSU-NLP-Group/LLM4Chem#1]
After load the dataset, I find that there are some redundant tags, like "\<SMILES> \<SMILES> ...... \</SMILES> \</SMILES> ". In addition, I found it is hard to calculate the metrics using in the paper. So could you please open source the evaluation code to reproduce the experimental results. 
Thanks for your excellent work!

**Comment by btyu** [comment]
Hi, the redundant tag problem had been fixed. Please download the newest version.
We will upload the evaluation code soon and inform you once done.
Thank you very much for your interest!

**Comment by coffezhou** [comment]
> Hi, the redundant tag problem had been fixed. Please download the newest version. We will upload the evaluation code soon and inform you once done. Thank you very much for your interest!

Thanks for your reply and excellent work!

**Comment by btyu** [comment]
Hi, the code for evaluation and training has been uploaded. Please feel free to let us know if you had any questions.
