### ISSUE TITLE
Library requirements

### ISSUE THREAD

**Issue by pcardenasg** [OSU-NLP-Group/LLM4Chem#2]
I'm not being able to reproduce your results and it seems that, at least the primary errors I am getting, are due to problems with library versions. Would you mind uploading a requirementes.txt file please?

**Comment by btyu** [comment]
[requirements.txt](https://github.com/user-attachments/files/15660292/requirements.txt)

If you don't mind, could you please send the error message? Maybe I can pinpoint the question for you. Thanks.

**Comment by btyu** [comment]
Closing this issue due to no further update. Please feel free to reopen it if needed :)
