### ISSUE TITLE
Model usage for Property Prediction

### ISSUE THREAD

**Issue by kunaldahiya** [OSU-NLP-Group/LLM4Chem#6]
Hi,

Thanks for releasing the code. I was trying out the [trained model](https://huggingface.co/osunlp/LlaSMol-Mistral-7B) for Property Prediction - Clintox. I used the following snippet (as suggested).

```py
from generation import LlaSMolGeneration

generator = LlaSMolGeneration('osunlp/LlaSMol-Mistral-7B')
generator.generate('Is <SMILES> COC[C@@H](NC(C)=O)C(=O)NCC1=CC=CC=C1 </SMILES> toxic?')
```

It runs; however, it always responds with "No" for all the molecule in "data/raw/test/property_prediction-clintox.jsonl". Same issue was observed when I tried on some other molecules. Can you please look into this? Please let me know if I need to change something while running.

Thanks!

**Comment by btyu** [comment]
Thank you for bringing this to our attention. Since most compounds in the training data are not toxic, the model may have inevitably learned the bias and tend to respond "No". Larger-scale and more balanced training data would alleviate this problem. Thanks again for your interest.

**Comment by kunaldahiya** [comment]
Alright. Thanks for looking into this.
